    public class Bike{
       public String name='motor cycle';
       public String catogery='mountain';
       public String material='steel';
        public String description='A cycle with two wheels';
    
        public Bike(String name,String catogery,String material,String description) {
            this.name=name;
            this.catogery=catogery;
            this.material=material;
            this.description=description;
    
        }
}
